package graph

import (
	"crypto/sha256"
	"encoding/base64"
	"fmt"
)

// Fingerprint sha256 of certificate bytes
type Fingerprint [sha256.Size]byte

// HexString print Fingerprint as hex
func (fp *Fingerprint) HexString() string {
	return fmt.Sprintf("%X", *fp)
}

// FingerprintFromBytes returns a Fingerprint generated by the provided bytes
func FingerprintFromBytes(data []byte) Fingerprint {
	var fp Fingerprint
	if len(data) != sha256.Size {
		v("Data is not correct SHA256 size", data)
	}
	for i := 0; i < len(data) && i < len(fp); i++ {
		fp[i] = data[i]
	}
	return fp
}

// FingerprintFromB64 returns a Fingerprint from a base64 encoded hash string
func FingerprintFromB64(hash string) Fingerprint {
	data, err := base64.StdEncoding.DecodeString(hash)
	if err != nil {
		v(err)
	}
	return FingerprintFromBytes(data)
}

// B64Encode returns the b64 string of a Fingerprint
func (fp *Fingerprint) B64Encode() string {
	return base64.StdEncoding.EncodeToString(fp[:])
}
